name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1' # or '20.18.0'
          cache: 'npm' # pnpm/yarn if you use those

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Create backup of current version
            sudo rm -rf /var/www/html/myapp_backup
            sudo mv /var/www/html/myapp /var/www/html/myapp_backup 2>/dev/null || true
            sudo mkdir -p /var/www/html/myapp

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: 'build/*'
          target: '/var/www/html/myapp'
          strip_components: 1

      - name: Set permissions
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo chown -R nginx:nginx /var/www/html/myapp
            sudo systemctl reload nginx
